---
abstract: 'a modern perl interactive shell'
author:
  - 'Matt S Trout - mst (at) shadowcatsystems.co.uk (L<http://www.shadowcatsystems.co.uk/>)'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-REPL
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  App::Nopaste: 0
  B::Concise: 0
  B::Keywords: 0
  Data::Dump::Streamer: 0
  Data::Dumper::Concise: 0
  Devel::Peek: 0
  File::HomeDir: 0
  File::Next: 0
  File::Spec: 0
  Lexical::Persistence: 0
  Module::Refresh: 0
  Moose: 0.93
  MooseX::Getopt: 0.18
  MooseX::Object::Pluggable: 0.0009
  PPI: 0
  Sys::SigAction: 0
  Task::Weaken: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.003014
